/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6de47c77ee5888a5c37165a5c18a8579)
interface __BaseEnv_Env {
  DB: D1Database;
  TELEMETRY_ANALYTICS: AnalyticsEngineDataset;
  NOTIFICATION_QUEUE: Queue;
  AI: Ai;
  WORKFLOW_LLM_MODEL: "@cf/qwen/qwen2.5-coder-32b-instruct";
  WORKFLOW_CODE_MODEL: "@cf/qwen/qwen2.5-coder-32b-instruct";
  AUTH0_ORGANIZATION_ID: "organization:production" | "organization:staging";
  AUTH0_ORGANIZATION_CLAIM?: "org_id";
  ACTION_EXECUTION_MODE: "execute";
  OPENFGA_API_URL: "https://api.us1.fga.dev";
  OPENFGA_ASSUME_LIST_USERS_COMPLETE: "false";
  ANALYTICS_ENGINE_ACCOUNT_ID: "e3e66e02919ba2916b412cba4009f5c0";
  TELEMETRY_DATASET: "ultra_easy_telemetry_production" | "ultra_easy_telemetry_staging";
  ACTION_AUTHORIZER:
    | Service /* entrypoint StagingActionAuthorizer from ultra-easy-approval-api-production */
    | Service<typeof import("./src/index").StagingActionAuthorizer>;
  ACTION_EXECUTOR:
    | Service /* entrypoint StagingActionExecutor from ultra-easy-approval-api-production */
    | Service<typeof import("./src/index").StagingActionExecutor>;
  ACTION_WORKFLOW: Workflow<Parameters<import("./src/index").ActionWorkflow["run"]>[0]["payload"]>;
  WORKFLOW_RUNNER: Workflow<Parameters<import("./src/index").WorkflowRunner["run"]>[0]["payload"]>;
  AUTH0_DOMAIN?: "dev-67c6cfj2y51bmeyf.us.auth0.com";
  AUTH0_API_AUDIENCE?: "https://ultra-easy/approval-api";
  AUTH0_TENANT_IS_ORGANIZATION?: "true";
  OPENFGA_STORE_ID?: "01M31PMZ0DRBWZQ9D6TZ64E87W";
  OPENFGA_AUTHORIZATION_MODEL_ID?: "01M3C9612ARE2Q84RTT6QBFMSA";
  AUTHORIZATION_MODEL_SOURCE_REVISION?: "f7f4bbd";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface ProductionEnv {
    DB: D1Database;
    TELEMETRY_ANALYTICS: AnalyticsEngineDataset;
    NOTIFICATION_QUEUE: Queue;
    AI: Ai;
    WORKFLOW_LLM_MODEL: "@cf/qwen/qwen2.5-coder-32b-instruct";
    WORKFLOW_CODE_MODEL: "@cf/qwen/qwen2.5-coder-32b-instruct";
    AUTH0_ORGANIZATION_ID: "organization:production";
    AUTH0_ORGANIZATION_CLAIM: "org_id";
    ACTION_EXECUTION_MODE: "execute";
    OPENFGA_API_URL: "https://api.us1.fga.dev";
    OPENFGA_ASSUME_LIST_USERS_COMPLETE: "false";
    ANALYTICS_ENGINE_ACCOUNT_ID: "e3e66e02919ba2916b412cba4009f5c0";
    TELEMETRY_DATASET: "ultra_easy_telemetry_production";
    ACTION_AUTHORIZER: Service /* entrypoint StagingActionAuthorizer from ultra-easy-approval-api-production */;
    ACTION_EXECUTOR: Service /* entrypoint StagingActionExecutor from ultra-easy-approval-api-production */;
    ACTION_WORKFLOW: Workflow<
      Parameters<import("./src/index").ActionWorkflow["run"]>[0]["payload"]
    >;
    WORKFLOW_RUNNER: Workflow<
      Parameters<import("./src/index").WorkflowRunner["run"]>[0]["payload"]
    >;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "WORKFLOW_LLM_MODEL"
      | "WORKFLOW_CODE_MODEL"
      | "AUTH0_ORGANIZATION_ID"
      | "AUTH0_ORGANIZATION_CLAIM"
      | "ACTION_EXECUTION_MODE"
      | "OPENFGA_API_URL"
      | "OPENFGA_ASSUME_LIST_USERS_COMPLETE"
      | "ANALYTICS_ENGINE_ACCOUNT_ID"
      | "TELEMETRY_DATASET"
      | "AUTH0_DOMAIN"
      | "AUTH0_API_AUDIENCE"
      | "AUTH0_TENANT_IS_ORGANIZATION"
      | "OPENFGA_STORE_ID"
      | "OPENFGA_AUTHORIZATION_MODEL_ID"
      | "AUTHORIZATION_MODEL_SOURCE_REVISION"
    >
  > {}
}
declare module "*.wasm" {
  const value: WebAssembly.Module;
  export default value;
}
