/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActionRequestsActionRequestIdRouteImport } from './routes/action-requests.$actionRequestId'
import { Route as AdminAuthorizationRouteImport } from './routes/admin.authorization'
import { Route as ApiActionRequestsRouteImport } from './routes/api.action-requests'
import { Route as ApprovalTasksTaskIdRouteImport } from './routes/approval-tasks.$taskId'
import { Route as PreviewApprovalRuntimeRouteImport } from './routes/preview.approval-runtime'
import { Route as PreviewOperatorDashboardRouteImport } from './routes/preview.operator-dashboard'
import { Route as WorkflowRunsRunIdRouteImport } from './routes/workflow-runs.$runId'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as AdminAuthorizationIndexRouteImport } from './routes/admin.authorization.index'
import { Route as AdminAuthorizationAuditRouteImport } from './routes/admin.authorization.audit'
import { Route as AdminAuthorizationExplorerRouteImport } from './routes/admin.authorization.explorer'
import { Route as AdminAuthorizationModelRouteImport } from './routes/admin.authorization.model'
import { Route as AdminAuthorizationRelationshipsRouteImport } from './routes/admin.authorization.relationships'
import { Route as ApiActionRequestsIdRouteImport } from './routes/api.action-requests.$id'
import { Route as ApiApprovalTasksTaskIdRouteImport } from './routes/api.approval-tasks.$taskId'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiPreviewApprovalRunsRouteImport } from './routes/api.preview.approval-runs'
import { Route as ApiPreviewOperatorDashboardRouteImport } from './routes/api.preview.operator-dashboard'
import { Route as ApiWorkflowSplatRouteImport } from './routes/api.workflow.$'
import { Route as PreviewWorkflowRunsRunIdRouteImport } from './routes/preview.workflow-runs.$runId'
import { Route as PreviewWorkflowsIndexRouteImport } from './routes/preview.workflows.index'
import { Route as PreviewWorkflowsIdRouteImport } from './routes/preview.workflows.$id'
import { Route as ApiActionRequestsIdTasksRouteImport } from './routes/api.action-requests.$id.tasks'
import { Route as ApiAdminAuthorizationSplatRouteImport } from './routes/api.admin.authorization.$'
import { Route as ApiApprovalTasksTaskIdDecisionsRouteImport } from './routes/api.approval-tasks.$taskId.decisions'
import { Route as ApiPreviewApprovalRunsIdRouteImport } from './routes/api.preview.approval-runs.$id'
import { Route as ApiPreviewWorkflowSplatRouteImport } from './routes/api.preview.workflow.$'
import { Route as ApiPreviewApprovalRunsIdDecisionsRouteImport } from './routes/api.preview.approval-runs.$id.decisions'
import { Route as ApiPreviewApprovalRunsIdForceCancelRouteImport } from './routes/api.preview.approval-runs.$id.force-cancel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRequestsActionRequestIdRoute =
  ActionRequestsActionRequestIdRouteImport.update({
    id: '/action-requests/$actionRequestId',
    path: '/action-requests/$actionRequestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAuthorizationRoute = AdminAuthorizationRouteImport.update({
  id: '/admin/authorization',
  path: '/admin/authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRequestsRoute = ApiActionRequestsRouteImport.update({
  id: '/api/action-requests',
  path: '/api/action-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalTasksTaskIdRoute = ApprovalTasksTaskIdRouteImport.update({
  id: '/approval-tasks/$taskId',
  path: '/approval-tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewApprovalRuntimeRoute = PreviewApprovalRuntimeRouteImport.update({
  id: '/preview/approval-runtime',
  path: '/preview/approval-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewOperatorDashboardRoute =
  PreviewOperatorDashboardRouteImport.update({
    id: '/preview/operator-dashboard',
    path: '/preview/operator-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowRunsRunIdRoute = WorkflowRunsRunIdRouteImport.update({
  id: '/workflow-runs/$runId',
  path: '/workflow-runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorizationIndexRoute = AdminAuthorizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthorizationRoute,
} as any)
const AdminAuthorizationAuditRoute = AdminAuthorizationAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAuthorizationRoute,
} as any)
const AdminAuthorizationExplorerRoute =
  AdminAuthorizationExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AdminAuthorizationRoute,
  } as any)
const AdminAuthorizationModelRoute = AdminAuthorizationModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AdminAuthorizationRoute,
} as any)
const AdminAuthorizationRelationshipsRoute =
  AdminAuthorizationRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => AdminAuthorizationRoute,
  } as any)
const ApiActionRequestsIdRoute = ApiActionRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiActionRequestsRoute,
} as any)
const ApiApprovalTasksTaskIdRoute = ApiApprovalTasksTaskIdRouteImport.update({
  id: '/api/approval-tasks/$taskId',
  path: '/api/approval-tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewApprovalRunsRoute = ApiPreviewApprovalRunsRouteImport.update({
  id: '/api/preview/approval-runs',
  path: '/api/preview/approval-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewOperatorDashboardRoute =
  ApiPreviewOperatorDashboardRouteImport.update({
    id: '/api/preview/operator-dashboard',
    path: '/api/preview/operator-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowSplatRoute = ApiWorkflowSplatRouteImport.update({
  id: '/api/workflow/$',
  path: '/api/workflow/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewWorkflowRunsRunIdRoute =
  PreviewWorkflowRunsRunIdRouteImport.update({
    id: '/preview/workflow-runs/$runId',
    path: '/preview/workflow-runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewWorkflowsIndexRoute = PreviewWorkflowsIndexRouteImport.update({
  id: '/preview/workflows/',
  path: '/preview/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewWorkflowsIdRoute = PreviewWorkflowsIdRouteImport.update({
  id: '/preview/workflows/$id',
  path: '/preview/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRequestsIdTasksRoute =
  ApiActionRequestsIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ApiActionRequestsIdRoute,
  } as any)
const ApiAdminAuthorizationSplatRoute =
  ApiAdminAuthorizationSplatRouteImport.update({
    id: '/api/admin/authorization/$',
    path: '/api/admin/authorization/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApprovalTasksTaskIdDecisionsRoute =
  ApiApprovalTasksTaskIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => ApiApprovalTasksTaskIdRoute,
  } as any)
const ApiPreviewApprovalRunsIdRoute =
  ApiPreviewApprovalRunsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPreviewApprovalRunsRoute,
  } as any)
const ApiPreviewWorkflowSplatRoute = ApiPreviewWorkflowSplatRouteImport.update({
  id: '/api/preview/workflow/$',
  path: '/api/preview/workflow/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewApprovalRunsIdDecisionsRoute =
  ApiPreviewApprovalRunsIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => ApiPreviewApprovalRunsIdRoute,
  } as any)
const ApiPreviewApprovalRunsIdForceCancelRoute =
  ApiPreviewApprovalRunsIdForceCancelRouteImport.update({
    id: '/force-cancel',
    path: '/force-cancel',
    getParentRoute: () => ApiPreviewApprovalRunsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-requests/$actionRequestId': typeof ActionRequestsActionRequestIdRoute
  '/admin/authorization': typeof AdminAuthorizationRouteWithChildren
  '/api/action-requests': typeof ApiActionRequestsRouteWithChildren
  '/approval-tasks/$taskId': typeof ApprovalTasksTaskIdRoute
  '/preview/approval-runtime': typeof PreviewApprovalRuntimeRoute
  '/preview/operator-dashboard': typeof PreviewOperatorDashboardRoute
  '/workflow-runs/$runId': typeof WorkflowRunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/admin/authorization/audit': typeof AdminAuthorizationAuditRoute
  '/admin/authorization/explorer': typeof AdminAuthorizationExplorerRoute
  '/admin/authorization/model': typeof AdminAuthorizationModelRoute
  '/admin/authorization/relationships': typeof AdminAuthorizationRelationshipsRoute
  '/api/action-requests/$id': typeof ApiActionRequestsIdRouteWithChildren
  '/api/approval-tasks/$taskId': typeof ApiApprovalTasksTaskIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/preview/approval-runs': typeof ApiPreviewApprovalRunsRouteWithChildren
  '/api/preview/operator-dashboard': typeof ApiPreviewOperatorDashboardRoute
  '/api/workflow/$': typeof ApiWorkflowSplatRoute
  '/preview/workflow-runs/$runId': typeof PreviewWorkflowRunsRunIdRoute
  '/preview/workflows/$id': typeof PreviewWorkflowsIdRoute
  '/admin/authorization/': typeof AdminAuthorizationIndexRoute
  '/preview/workflows/': typeof PreviewWorkflowsIndexRoute
  '/api/action-requests/$id/tasks': typeof ApiActionRequestsIdTasksRoute
  '/api/admin/authorization/$': typeof ApiAdminAuthorizationSplatRoute
  '/api/approval-tasks/$taskId/decisions': typeof ApiApprovalTasksTaskIdDecisionsRoute
  '/api/preview/approval-runs/$id': typeof ApiPreviewApprovalRunsIdRouteWithChildren
  '/api/preview/workflow/$': typeof ApiPreviewWorkflowSplatRoute
  '/api/preview/approval-runs/$id/decisions': typeof ApiPreviewApprovalRunsIdDecisionsRoute
  '/api/preview/approval-runs/$id/force-cancel': typeof ApiPreviewApprovalRunsIdForceCancelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-requests/$actionRequestId': typeof ActionRequestsActionRequestIdRoute
  '/api/action-requests': typeof ApiActionRequestsRouteWithChildren
  '/approval-tasks/$taskId': typeof ApprovalTasksTaskIdRoute
  '/preview/approval-runtime': typeof PreviewApprovalRuntimeRoute
  '/preview/operator-dashboard': typeof PreviewOperatorDashboardRoute
  '/workflow-runs/$runId': typeof WorkflowRunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/admin/authorization/audit': typeof AdminAuthorizationAuditRoute
  '/admin/authorization/explorer': typeof AdminAuthorizationExplorerRoute
  '/admin/authorization/model': typeof AdminAuthorizationModelRoute
  '/admin/authorization/relationships': typeof AdminAuthorizationRelationshipsRoute
  '/api/action-requests/$id': typeof ApiActionRequestsIdRouteWithChildren
  '/api/approval-tasks/$taskId': typeof ApiApprovalTasksTaskIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/preview/approval-runs': typeof ApiPreviewApprovalRunsRouteWithChildren
  '/api/preview/operator-dashboard': typeof ApiPreviewOperatorDashboardRoute
  '/api/workflow/$': typeof ApiWorkflowSplatRoute
  '/preview/workflow-runs/$runId': typeof PreviewWorkflowRunsRunIdRoute
  '/preview/workflows/$id': typeof PreviewWorkflowsIdRoute
  '/admin/authorization': typeof AdminAuthorizationIndexRoute
  '/preview/workflows': typeof PreviewWorkflowsIndexRoute
  '/api/action-requests/$id/tasks': typeof ApiActionRequestsIdTasksRoute
  '/api/admin/authorization/$': typeof ApiAdminAuthorizationSplatRoute
  '/api/approval-tasks/$taskId/decisions': typeof ApiApprovalTasksTaskIdDecisionsRoute
  '/api/preview/approval-runs/$id': typeof ApiPreviewApprovalRunsIdRouteWithChildren
  '/api/preview/workflow/$': typeof ApiPreviewWorkflowSplatRoute
  '/api/preview/approval-runs/$id/decisions': typeof ApiPreviewApprovalRunsIdDecisionsRoute
  '/api/preview/approval-runs/$id/force-cancel': typeof ApiPreviewApprovalRunsIdForceCancelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-requests/$actionRequestId': typeof ActionRequestsActionRequestIdRoute
  '/admin/authorization': typeof AdminAuthorizationRouteWithChildren
  '/api/action-requests': typeof ApiActionRequestsRouteWithChildren
  '/approval-tasks/$taskId': typeof ApprovalTasksTaskIdRoute
  '/preview/approval-runtime': typeof PreviewApprovalRuntimeRoute
  '/preview/operator-dashboard': typeof PreviewOperatorDashboardRoute
  '/workflow-runs/$runId': typeof WorkflowRunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/admin/authorization/audit': typeof AdminAuthorizationAuditRoute
  '/admin/authorization/explorer': typeof AdminAuthorizationExplorerRoute
  '/admin/authorization/model': typeof AdminAuthorizationModelRoute
  '/admin/authorization/relationships': typeof AdminAuthorizationRelationshipsRoute
  '/api/action-requests/$id': typeof ApiActionRequestsIdRouteWithChildren
  '/api/approval-tasks/$taskId': typeof ApiApprovalTasksTaskIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/preview/approval-runs': typeof ApiPreviewApprovalRunsRouteWithChildren
  '/api/preview/operator-dashboard': typeof ApiPreviewOperatorDashboardRoute
  '/api/workflow/$': typeof ApiWorkflowSplatRoute
  '/preview/workflow-runs/$runId': typeof PreviewWorkflowRunsRunIdRoute
  '/preview/workflows/$id': typeof PreviewWorkflowsIdRoute
  '/admin/authorization/': typeof AdminAuthorizationIndexRoute
  '/preview/workflows/': typeof PreviewWorkflowsIndexRoute
  '/api/action-requests/$id/tasks': typeof ApiActionRequestsIdTasksRoute
  '/api/admin/authorization/$': typeof ApiAdminAuthorizationSplatRoute
  '/api/approval-tasks/$taskId/decisions': typeof ApiApprovalTasksTaskIdDecisionsRoute
  '/api/preview/approval-runs/$id': typeof ApiPreviewApprovalRunsIdRouteWithChildren
  '/api/preview/workflow/$': typeof ApiPreviewWorkflowSplatRoute
  '/api/preview/approval-runs/$id/decisions': typeof ApiPreviewApprovalRunsIdDecisionsRoute
  '/api/preview/approval-runs/$id/force-cancel': typeof ApiPreviewApprovalRunsIdForceCancelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/action-requests/$actionRequestId'
    | '/admin/authorization'
    | '/api/action-requests'
    | '/approval-tasks/$taskId'
    | '/preview/approval-runtime'
    | '/preview/operator-dashboard'
    | '/workflow-runs/$runId'
    | '/workflows/$id'
    | '/workflows/'
    | '/admin/authorization/audit'
    | '/admin/authorization/explorer'
    | '/admin/authorization/model'
    | '/admin/authorization/relationships'
    | '/api/action-requests/$id'
    | '/api/approval-tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/preview/approval-runs'
    | '/api/preview/operator-dashboard'
    | '/api/workflow/$'
    | '/preview/workflow-runs/$runId'
    | '/preview/workflows/$id'
    | '/admin/authorization/'
    | '/preview/workflows/'
    | '/api/action-requests/$id/tasks'
    | '/api/admin/authorization/$'
    | '/api/approval-tasks/$taskId/decisions'
    | '/api/preview/approval-runs/$id'
    | '/api/preview/workflow/$'
    | '/api/preview/approval-runs/$id/decisions'
    | '/api/preview/approval-runs/$id/force-cancel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/action-requests/$actionRequestId'
    | '/api/action-requests'
    | '/approval-tasks/$taskId'
    | '/preview/approval-runtime'
    | '/preview/operator-dashboard'
    | '/workflow-runs/$runId'
    | '/workflows/$id'
    | '/workflows'
    | '/admin/authorization/audit'
    | '/admin/authorization/explorer'
    | '/admin/authorization/model'
    | '/admin/authorization/relationships'
    | '/api/action-requests/$id'
    | '/api/approval-tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/preview/approval-runs'
    | '/api/preview/operator-dashboard'
    | '/api/workflow/$'
    | '/preview/workflow-runs/$runId'
    | '/preview/workflows/$id'
    | '/admin/authorization'
    | '/preview/workflows'
    | '/api/action-requests/$id/tasks'
    | '/api/admin/authorization/$'
    | '/api/approval-tasks/$taskId/decisions'
    | '/api/preview/approval-runs/$id'
    | '/api/preview/workflow/$'
    | '/api/preview/approval-runs/$id/decisions'
    | '/api/preview/approval-runs/$id/force-cancel'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/action-requests/$actionRequestId'
    | '/admin/authorization'
    | '/api/action-requests'
    | '/approval-tasks/$taskId'
    | '/preview/approval-runtime'
    | '/preview/operator-dashboard'
    | '/workflow-runs/$runId'
    | '/workflows/$id'
    | '/workflows/'
    | '/admin/authorization/audit'
    | '/admin/authorization/explorer'
    | '/admin/authorization/model'
    | '/admin/authorization/relationships'
    | '/api/action-requests/$id'
    | '/api/approval-tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/preview/approval-runs'
    | '/api/preview/operator-dashboard'
    | '/api/workflow/$'
    | '/preview/workflow-runs/$runId'
    | '/preview/workflows/$id'
    | '/admin/authorization/'
    | '/preview/workflows/'
    | '/api/action-requests/$id/tasks'
    | '/api/admin/authorization/$'
    | '/api/approval-tasks/$taskId/decisions'
    | '/api/preview/approval-runs/$id'
    | '/api/preview/workflow/$'
    | '/api/preview/approval-runs/$id/decisions'
    | '/api/preview/approval-runs/$id/force-cancel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ActionRequestsActionRequestIdRoute: typeof ActionRequestsActionRequestIdRoute
  AdminAuthorizationRoute: typeof AdminAuthorizationRouteWithChildren
  ApiActionRequestsRoute: typeof ApiActionRequestsRouteWithChildren
  ApprovalTasksTaskIdRoute: typeof ApprovalTasksTaskIdRoute
  PreviewApprovalRuntimeRoute: typeof PreviewApprovalRuntimeRoute
  PreviewOperatorDashboardRoute: typeof PreviewOperatorDashboardRoute
  WorkflowRunsRunIdRoute: typeof WorkflowRunsRunIdRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiApprovalTasksTaskIdRoute: typeof ApiApprovalTasksTaskIdRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiPreviewApprovalRunsRoute: typeof ApiPreviewApprovalRunsRouteWithChildren
  ApiPreviewOperatorDashboardRoute: typeof ApiPreviewOperatorDashboardRoute
  ApiWorkflowSplatRoute: typeof ApiWorkflowSplatRoute
  PreviewWorkflowRunsRunIdRoute: typeof PreviewWorkflowRunsRunIdRoute
  PreviewWorkflowsIdRoute: typeof PreviewWorkflowsIdRoute
  PreviewWorkflowsIndexRoute: typeof PreviewWorkflowsIndexRoute
  ApiAdminAuthorizationSplatRoute: typeof ApiAdminAuthorizationSplatRoute
  ApiPreviewWorkflowSplatRoute: typeof ApiPreviewWorkflowSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-requests/$actionRequestId': {
      id: '/action-requests/$actionRequestId'
      path: '/action-requests/$actionRequestId'
      fullPath: '/action-requests/$actionRequestId'
      preLoaderRoute: typeof ActionRequestsActionRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authorization': {
      id: '/admin/authorization'
      path: '/admin/authorization'
      fullPath: '/admin/authorization'
      preLoaderRoute: typeof AdminAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action-requests': {
      id: '/api/action-requests'
      path: '/api/action-requests'
      fullPath: '/api/action-requests'
      preLoaderRoute: typeof ApiActionRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-tasks/$taskId': {
      id: '/approval-tasks/$taskId'
      path: '/approval-tasks/$taskId'
      fullPath: '/approval-tasks/$taskId'
      preLoaderRoute: typeof ApprovalTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/approval-runtime': {
      id: '/preview/approval-runtime'
      path: '/preview/approval-runtime'
      fullPath: '/preview/approval-runtime'
      preLoaderRoute: typeof PreviewApprovalRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/operator-dashboard': {
      id: '/preview/operator-dashboard'
      path: '/preview/operator-dashboard'
      fullPath: '/preview/operator-dashboard'
      preLoaderRoute: typeof PreviewOperatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-runs/$runId': {
      id: '/workflow-runs/$runId'
      path: '/workflow-runs/$runId'
      fullPath: '/workflow-runs/$runId'
      preLoaderRoute: typeof WorkflowRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authorization/': {
      id: '/admin/authorization/'
      path: '/'
      fullPath: '/admin/authorization/'
      preLoaderRoute: typeof AdminAuthorizationIndexRouteImport
      parentRoute: typeof AdminAuthorizationRoute
    }
    '/admin/authorization/audit': {
      id: '/admin/authorization/audit'
      path: '/audit'
      fullPath: '/admin/authorization/audit'
      preLoaderRoute: typeof AdminAuthorizationAuditRouteImport
      parentRoute: typeof AdminAuthorizationRoute
    }
    '/admin/authorization/explorer': {
      id: '/admin/authorization/explorer'
      path: '/explorer'
      fullPath: '/admin/authorization/explorer'
      preLoaderRoute: typeof AdminAuthorizationExplorerRouteImport
      parentRoute: typeof AdminAuthorizationRoute
    }
    '/admin/authorization/model': {
      id: '/admin/authorization/model'
      path: '/model'
      fullPath: '/admin/authorization/model'
      preLoaderRoute: typeof AdminAuthorizationModelRouteImport
      parentRoute: typeof AdminAuthorizationRoute
    }
    '/admin/authorization/relationships': {
      id: '/admin/authorization/relationships'
      path: '/relationships'
      fullPath: '/admin/authorization/relationships'
      preLoaderRoute: typeof AdminAuthorizationRelationshipsRouteImport
      parentRoute: typeof AdminAuthorizationRoute
    }
    '/api/action-requests/$id': {
      id: '/api/action-requests/$id'
      path: '/$id'
      fullPath: '/api/action-requests/$id'
      preLoaderRoute: typeof ApiActionRequestsIdRouteImport
      parentRoute: typeof ApiActionRequestsRoute
    }
    '/api/approval-tasks/$taskId': {
      id: '/api/approval-tasks/$taskId'
      path: '/api/approval-tasks/$taskId'
      fullPath: '/api/approval-tasks/$taskId'
      preLoaderRoute: typeof ApiApprovalTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/approval-runs': {
      id: '/api/preview/approval-runs'
      path: '/api/preview/approval-runs'
      fullPath: '/api/preview/approval-runs'
      preLoaderRoute: typeof ApiPreviewApprovalRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/operator-dashboard': {
      id: '/api/preview/operator-dashboard'
      path: '/api/preview/operator-dashboard'
      fullPath: '/api/preview/operator-dashboard'
      preLoaderRoute: typeof ApiPreviewOperatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/$': {
      id: '/api/workflow/$'
      path: '/api/workflow/$'
      fullPath: '/api/workflow/$'
      preLoaderRoute: typeof ApiWorkflowSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/workflow-runs/$runId': {
      id: '/preview/workflow-runs/$runId'
      path: '/preview/workflow-runs/$runId'
      fullPath: '/preview/workflow-runs/$runId'
      preLoaderRoute: typeof PreviewWorkflowRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/workflows/': {
      id: '/preview/workflows/'
      path: '/preview/workflows'
      fullPath: '/preview/workflows/'
      preLoaderRoute: typeof PreviewWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/workflows/$id': {
      id: '/preview/workflows/$id'
      path: '/preview/workflows/$id'
      fullPath: '/preview/workflows/$id'
      preLoaderRoute: typeof PreviewWorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action-requests/$id/tasks': {
      id: '/api/action-requests/$id/tasks'
      path: '/tasks'
      fullPath: '/api/action-requests/$id/tasks'
      preLoaderRoute: typeof ApiActionRequestsIdTasksRouteImport
      parentRoute: typeof ApiActionRequestsIdRoute
    }
    '/api/admin/authorization/$': {
      id: '/api/admin/authorization/$'
      path: '/api/admin/authorization/$'
      fullPath: '/api/admin/authorization/$'
      preLoaderRoute: typeof ApiAdminAuthorizationSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approval-tasks/$taskId/decisions': {
      id: '/api/approval-tasks/$taskId/decisions'
      path: '/decisions'
      fullPath: '/api/approval-tasks/$taskId/decisions'
      preLoaderRoute: typeof ApiApprovalTasksTaskIdDecisionsRouteImport
      parentRoute: typeof ApiApprovalTasksTaskIdRoute
    }
    '/api/preview/approval-runs/$id': {
      id: '/api/preview/approval-runs/$id'
      path: '/$id'
      fullPath: '/api/preview/approval-runs/$id'
      preLoaderRoute: typeof ApiPreviewApprovalRunsIdRouteImport
      parentRoute: typeof ApiPreviewApprovalRunsRoute
    }
    '/api/preview/workflow/$': {
      id: '/api/preview/workflow/$'
      path: '/api/preview/workflow/$'
      fullPath: '/api/preview/workflow/$'
      preLoaderRoute: typeof ApiPreviewWorkflowSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/approval-runs/$id/decisions': {
      id: '/api/preview/approval-runs/$id/decisions'
      path: '/decisions'
      fullPath: '/api/preview/approval-runs/$id/decisions'
      preLoaderRoute: typeof ApiPreviewApprovalRunsIdDecisionsRouteImport
      parentRoute: typeof ApiPreviewApprovalRunsIdRoute
    }
    '/api/preview/approval-runs/$id/force-cancel': {
      id: '/api/preview/approval-runs/$id/force-cancel'
      path: '/force-cancel'
      fullPath: '/api/preview/approval-runs/$id/force-cancel'
      preLoaderRoute: typeof ApiPreviewApprovalRunsIdForceCancelRouteImport
      parentRoute: typeof ApiPreviewApprovalRunsIdRoute
    }
  }
}

interface AdminAuthorizationRouteChildren {
  AdminAuthorizationAuditRoute: typeof AdminAuthorizationAuditRoute
  AdminAuthorizationExplorerRoute: typeof AdminAuthorizationExplorerRoute
  AdminAuthorizationModelRoute: typeof AdminAuthorizationModelRoute
  AdminAuthorizationRelationshipsRoute: typeof AdminAuthorizationRelationshipsRoute
  AdminAuthorizationIndexRoute: typeof AdminAuthorizationIndexRoute
}

const AdminAuthorizationRouteChildren: AdminAuthorizationRouteChildren = {
  AdminAuthorizationAuditRoute: AdminAuthorizationAuditRoute,
  AdminAuthorizationExplorerRoute: AdminAuthorizationExplorerRoute,
  AdminAuthorizationModelRoute: AdminAuthorizationModelRoute,
  AdminAuthorizationRelationshipsRoute: AdminAuthorizationRelationshipsRoute,
  AdminAuthorizationIndexRoute: AdminAuthorizationIndexRoute,
}

const AdminAuthorizationRouteWithChildren =
  AdminAuthorizationRoute._addFileChildren(AdminAuthorizationRouteChildren)

interface ApiActionRequestsIdRouteChildren {
  ApiActionRequestsIdTasksRoute: typeof ApiActionRequestsIdTasksRoute
}

const ApiActionRequestsIdRouteChildren: ApiActionRequestsIdRouteChildren = {
  ApiActionRequestsIdTasksRoute: ApiActionRequestsIdTasksRoute,
}

const ApiActionRequestsIdRouteWithChildren =
  ApiActionRequestsIdRoute._addFileChildren(ApiActionRequestsIdRouteChildren)

interface ApiActionRequestsRouteChildren {
  ApiActionRequestsIdRoute: typeof ApiActionRequestsIdRouteWithChildren
}

const ApiActionRequestsRouteChildren: ApiActionRequestsRouteChildren = {
  ApiActionRequestsIdRoute: ApiActionRequestsIdRouteWithChildren,
}

const ApiActionRequestsRouteWithChildren =
  ApiActionRequestsRoute._addFileChildren(ApiActionRequestsRouteChildren)

interface ApiApprovalTasksTaskIdRouteChildren {
  ApiApprovalTasksTaskIdDecisionsRoute: typeof ApiApprovalTasksTaskIdDecisionsRoute
}

const ApiApprovalTasksTaskIdRouteChildren: ApiApprovalTasksTaskIdRouteChildren =
  {
    ApiApprovalTasksTaskIdDecisionsRoute: ApiApprovalTasksTaskIdDecisionsRoute,
  }

const ApiApprovalTasksTaskIdRouteWithChildren =
  ApiApprovalTasksTaskIdRoute._addFileChildren(
    ApiApprovalTasksTaskIdRouteChildren,
  )

interface ApiPreviewApprovalRunsIdRouteChildren {
  ApiPreviewApprovalRunsIdDecisionsRoute: typeof ApiPreviewApprovalRunsIdDecisionsRoute
  ApiPreviewApprovalRunsIdForceCancelRoute: typeof ApiPreviewApprovalRunsIdForceCancelRoute
}

const ApiPreviewApprovalRunsIdRouteChildren: ApiPreviewApprovalRunsIdRouteChildren =
  {
    ApiPreviewApprovalRunsIdDecisionsRoute:
      ApiPreviewApprovalRunsIdDecisionsRoute,
    ApiPreviewApprovalRunsIdForceCancelRoute:
      ApiPreviewApprovalRunsIdForceCancelRoute,
  }

const ApiPreviewApprovalRunsIdRouteWithChildren =
  ApiPreviewApprovalRunsIdRoute._addFileChildren(
    ApiPreviewApprovalRunsIdRouteChildren,
  )

interface ApiPreviewApprovalRunsRouteChildren {
  ApiPreviewApprovalRunsIdRoute: typeof ApiPreviewApprovalRunsIdRouteWithChildren
}

const ApiPreviewApprovalRunsRouteChildren: ApiPreviewApprovalRunsRouteChildren =
  {
    ApiPreviewApprovalRunsIdRoute: ApiPreviewApprovalRunsIdRouteWithChildren,
  }

const ApiPreviewApprovalRunsRouteWithChildren =
  ApiPreviewApprovalRunsRoute._addFileChildren(
    ApiPreviewApprovalRunsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ActionRequestsActionRequestIdRoute: ActionRequestsActionRequestIdRoute,
  AdminAuthorizationRoute: AdminAuthorizationRouteWithChildren,
  ApiActionRequestsRoute: ApiActionRequestsRouteWithChildren,
  ApprovalTasksTaskIdRoute: ApprovalTasksTaskIdRoute,
  PreviewApprovalRuntimeRoute: PreviewApprovalRuntimeRoute,
  PreviewOperatorDashboardRoute: PreviewOperatorDashboardRoute,
  WorkflowRunsRunIdRoute: WorkflowRunsRunIdRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiApprovalTasksTaskIdRoute: ApiApprovalTasksTaskIdRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiPreviewApprovalRunsRoute: ApiPreviewApprovalRunsRouteWithChildren,
  ApiPreviewOperatorDashboardRoute: ApiPreviewOperatorDashboardRoute,
  ApiWorkflowSplatRoute: ApiWorkflowSplatRoute,
  PreviewWorkflowRunsRunIdRoute: PreviewWorkflowRunsRunIdRoute,
  PreviewWorkflowsIdRoute: PreviewWorkflowsIdRoute,
  PreviewWorkflowsIndexRoute: PreviewWorkflowsIndexRoute,
  ApiAdminAuthorizationSplatRoute: ApiAdminAuthorizationSplatRoute,
  ApiPreviewWorkflowSplatRoute: ApiPreviewWorkflowSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
